#!/usr/bin/python
import DMPSW
import libDmpAlgTrk as trackAlg 

#DMPSW.Core.Set("EventNumber","10")
DMPSW.RootIOSvc.Set("Input/FileName","/Volumes/data/Raw_BgoHits.root")

trkAlg = trackAlg.DmpAlgTrk()
DMPSW.AlgMgr.Append(trkAlg)

DMPSW.Core.Initialize()
#DMPSW.Core.ExecuteEventID(10)
DMPSW.Core.Run()
DMPSW.Core.Finalize()
